#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#


HQ_PROJECT_NAME ?= a2010
ifeq ($(HQ_PROJECT_NAME),a2010)
	obj-y += gc2355mipi_Sensor_a2010.o
else
	obj-y	+= gc2355mipi_Sensor.o
endif

